version: '3'

services:
  #  app:
  #    build: .
  #    restart: always
  #    container_name: catalog_app
  #    ports:
  #      - 3000:3000
  #    depends_on:
  #      - db
  db:
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalog-lite
    ports:
      - 5432:5432
#    volumes:
#      - db-data3:/var/lib/postgresql/data

#volumes:
#  db-data3:
#    driver: local