version: '3'

services:
  app:
    build: .
    restart: always
    container_name: catalog_lite_app
    environment:
      PORT: 3000
      DB_HOST: db
      DB_NAME: catalog_lite
      DB_USER: postgres
      DB_PASS: postgres
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: kartoza/postgis:12.0
    restart: always
    container_name: catalog_lite_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalog_lite
    ports:
      - 5432:5432
    volumes:
      - ./resources/dump.sql:/docker-entrypoint-initdb.d/dump.sql
#      - db-data3:/var/lib/postgresql/data

#volumes:
#  db-data3:
#    driver: local